// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-villa-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var info = {
  name: "Villa Paola Caposuvero",
  location: "Gizzeria Lido, Calabria, Italy",
  description: "Premium seaside villa with direct/private beach access, garden, sea-view terrace. Pet-friendly, family-friendly, close to Lamezia Terme airport.",
  contacts: {
    whatsapp: "+39 335 538 4250",
    website: "https://villapaolacaposuvero.it"
  },
  features: [
    "Direct/private sea access",
    "Sea-view terrace and garden",
    "Pet-friendly (animals allowed)",
    "Family-friendly",
    "Close to Lamezia Terme airport"
  ],
  booking_channel: "No online booking. Availability is confirmed via WhatsApp, phone, or the availability request form on the website."
};
var get_villa_info_default = defineTool({
  name: "get_villa_info",
  title: "Get villa info",
  description: "Return essential facts about Villa Paola Caposuvero: location, features, contacts, and how to book.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
    structuredContent: info
  })
});

// src/lib/mcp/tools/list-reviews.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_reviews_default = defineTool2({
  name: "list_reviews",
  title: "List approved reviews",
  description: "Return the latest approved guest reviews for Villa Paola Caposuvero (public data).",
  inputSchema: {
    limit: z.number().int().default(10).describe("Maximum number of reviews to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const capped = Math.min(Math.max(limit ?? 10, 1), 50);
    const { data, error } = await sb().from("reviews").select("guest_name,rating,comment,stay_date,created_at").eq("status", "approved").order("created_at", { ascending: false }).limit(capped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-availability-request.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var submit_availability_request_default = defineTool3({
  name: "submit_availability_request",
  title: "Submit availability request",
  description: "Send a new availability/quote request for Villa Paola Caposuvero. The owner will follow up by email or WhatsApp; this does not confirm a booking.",
  inputSchema: {
    guest_name: z2.string().min(1).max(100).describe("Full name of the guest."),
    email: z2.string().email().max(200).describe("Contact email."),
    phone: z2.string().max(40).optional().describe("Phone number (with country code)."),
    arrival_date: z2.string().optional().describe("Requested arrival date (YYYY-MM-DD)."),
    departure_date: z2.string().optional().describe("Requested departure date (YYYY-MM-DD)."),
    guests_count: z2.number().int().optional().describe("Number of guests."),
    message: z2.string().max(1500).optional().describe("Free-form message or special requests.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input) => {
    const { data, error } = await sb2().from("leads").insert({
      guest_name: input.guest_name.trim(),
      email: input.email.trim(),
      phone: input.phone?.trim() || null,
      arrival_date: input.arrival_date || null,
      departure_date: input.departure_date || null,
      guests_count: input.guests_count ?? null,
      message: input.message?.trim() || null
    }).select("id,created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Request received (id ${data.id}). The owner will reply via email or WhatsApp.`
        }
      ],
      structuredContent: { id: data.id, created_at: data.created_at }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "villa-paola-mcp",
  title: "Villa Paola Caposuvero",
  version: "0.1.0",
  instructions: "Tools for Villa Paola Caposuvero, a seaside villa in Gizzeria (Calabria, Italy). Use `get_villa_info` for facts and contacts, `list_reviews` for guest reviews, and `submit_availability_request` to send an availability/quote request to the owner. There is no online booking \u2014 the owner confirms via WhatsApp or email.",
  tools: [get_villa_info_default, list_reviews_default, submit_availability_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
